name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      name: Check out code

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          3.1.x
          5.0.x
          6.0.x
          8.0.x
  
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: yovko93/my-portfolio-app
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        dockerfile: ./MyPortfolioApp/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: joelwmale/webhook-action@master
        name: Deploy to production
        env:
          WEBHOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL}}
