name: Docker Publish

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'  # Replace with the desired .NET SDK version

      - name: Install wasm-tools workload
        run: dotnet workload install wasm-tools
        
      - name: Create Docker configuration file
        run: |
          echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(echo -n $DOCKER_USERNAME:$DOCKER_PASSWORD | base64)\"}}}" > $HOME/.docker/config.json

      - name: Build and publish Docker image
        run: |
          docker build -t yovko93/my-portfolio-app ./MyPortfolioApp
          docker push yovko93/my-portfolio-app
