name: Build and Push Docker Image and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Replace with the desired .NET SDK version

    - name: Build Docker image
      run: |
        cp -r ./MyPortfolioApp/. ./MyPortfolioAppTemp
        docker build -t yovko93/my-portfolio-app:latest --file MyPortfolioApp/Dockerfile .

    - name: Push Docker image
      run: |
        docker push yovko93/my-portfolio-app:latest
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: build
    steps:
      - uses: joelwmale/webhook-action@master
        name: Deploy to production
        env:
          WEBHOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL}}
          
