name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/yovko93/my-portfolio-app ./MyPortfolioApp
          docker push ghcr.io/yovko93/my-portfolio-app
