name: Build and Push Docker Image and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Replace with the desired .NET SDK version

    - name: Build Docker image
      run: |
        cd MyPortfolioApp  # Move into the project directory
        dotnet restore  # Restore dependencies
        dotnet publish -c Release -o out  # Publish the application
        cd ..  # Move back to the root directory
        docker build -t yovko93/my-portfolio-app:latest ./MyPortfolioApp  # Build Docker image
    - name: Push Docker image
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        docker push yovko93/my-portfolio-app:latest
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: build
    steps:
      - uses: joelwmale/webhook-action@master
        name: Deploy to production
        env:
          WEBHOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL}}
          
