name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
     
      - name: Set up Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/yovko93/my-portfolio/portfolio-img:latest ./src
          docker push ghcr.io/yovko93/my-portfolio/portfolio-img:latest
